export const mockWords = [
  "vassals",
  "jungles",
  "laughed",
  "serving",
  "caliber",
  "current",
  "staying",
  "strange",
  "grenade",
  "friends",
  "outcome",
  "details",
  "passing",
  "tainted",
  "attacks",
].map((word) => word.toUpperCase());
